##
## Bolt Members configuration options
##

## Debugging ##################################################################
#
debug: false

## Template overrides #########################################################
forms:
    templates:
        profile:
            parent: partials/_profile.twig
            register: partials/_profile_register.twig
        authentication:
            parent: partials/_authentication.twig
            login: partials/_auth_login.twig
            recovery: partials/_auth_recovery.twig

## Registration ###############################################################
#
registration:
    enabled: true  # If registration should be allowed [true|false]

## Notification email addresses ###############################################
#
notification:
    name: Bolt Market Place   # Display name used as the sender name
    email: no-reply@bolt.cm   # Email address as the sender address

## Access Control #############################################################
#
roles:
    admin:
        - root
        - admin
        - developer
    member:
        admin: Administrator
        participant: Participant
    associate:
        - participant

## OAuth2 Providers ##########################################################
#
providers:
    local:
        label:
            sign_in: Sign in with a local account
            associate: --not applicable--
        enabled: true
        keys:
            client_id: localdefault
            client_secret: localdefault
        scopes: [ user ]
    github:
        label:
            sign_in: Sign in with GitHub
            associate: Add your GitHub account
        enabled: true
        keys:
            client_id:
            client_secret:
        scopes: [ user ]
