paths:
    web: %root%/web
    bolt_assets: %web%/bolt-web
    var: %root%/var
    cache: %var%/cache
    composer: %cache%/composer
    satis: %cache%/satis
extensions:
    - Bolt\Extension\Bolt\MarketPlace\MarketPlaceExtension
