pages:
    name: Pages
    singular_name: Page
    fields:
        title:
            type: text
            class: large
            group: content
        slug:
            type: slug
            uses: title
        image:
            type: image
        teaser:
            type: html
            height: 150px
        body:
            type: html
            height: 300px
        template:
            type: templateselect
            filter: '*.twig'
    taxonomy: [ groups ]
    recordsperpage: 100

collections:
    name: Collections
    singular_name: Collection
    fields:
        title:
            type: text
            class: large
            group: content
        slug:
            type: slug
            uses: title
        description:
            type: html
            height: 150px
        items:
            type: repeater
            group: Items
            limit: 50
            fields:
                repeattitle:
                    label: Extension Title (just intern)
                    type: text
                repeatextension:
                    label: Extension ID
                    type: text
                    required: true
                repeatdescription:
                    label: Description
                    type: html
    recordsperpage: 100
    sort: -datepublish

blocks:
    name: Blocks
    singular_name: Block
    fields:
        title:
            type: text
            class: large
            group: "Block"
        slug:
            type: slug
            uses: [ title ]
        content:
            type: html
            height: 150px
        contentlink:
            type: text
            label: Link
            placeholder: 'contenttype/slug or http://example.org/'
            postfix: "Use this to add a link for this Block. This could either be an 'internal' link like <tt>page/about</tt>, if you use a contenttype/slug combination. Otherwise use a proper URL, like `http://example.org`."
        image:
            type: image
            attrib: title
            extensions: [ gif, jpg, png ]
    show_on_dashboard: true
    viewless: true
    default_status: publish
    searchable: false
    icon_many: "fa:cubes"
    icon_one: "fa:cube"
