vcs:
    - https://github.com/guzzle/guzzle3.git
    - https://github.com/paragonie/random_compat.git
    - https://github.com/ramsey/uuid.git
    - https://github.com/wikimedia/composer-merge-plugin.git
    - https://github.com/KnpLabs/php-github-api.git
    - https://github.com/bolt/omnipay.git
    - https://github.com/whiteoctober/Pagerfanta.git
    - https://github.com/Exeu/apai-io.git
    - https://github.com/pusher/pusher-http-php.git
    - https://github.com/thephpleague/event.git
