vcs:
    - https://github.com/guzzle/guzzle3.git
    - https://github.com/paragonie/random_compat.git
    - https://github.com/ramsey/uuid.git
    - https://github.com/wikimedia/composer-merge-plugin.git
